### ISSUE TITLE
Descripción mejora o creación de funcionalidad

### ISSUE THREAD

**Issue by frasgado** [14030598/santander-back-proyecto#18]
## **Sientete con la libertad de editar esta issue conforme a tus necesidades**
Incorporar menú para desktop
Incorporar menú para tablet y mobile

### Descripción
Incorporar etiquetas de Semantic UI para menu 

**Establece un tiempo limite para terminar tu feature**
> 14-08-2021 23:59 GMT

### Tareas
- [ ] Tarea 1 Soporte a Desktop
- [ ] Tarea 2 Soporte a Table y mobile

**Solicita una mejora**
Descripción 
Si encuentran detalles, favor de indicarme.

**Comment by frasgado** [comment]
Se ha incorporado a desarrollo el soporte menu para desktop, tablet, y mobile.

**Comment by 14030598** [comment]
Ya es tiempo de cerrar esta mejora
