### ISSUE TITLE
Creacción de página con detalle de una receta

### ISSUE THREAD

**Issue by frasgado** [14030598/santander-back-proyecto#19]
### Descripción
Se crearan los componentes para la funcionalidad de mostrar receta con su imagen, ingredientes, instrucciones y video.
https://github.com/14030598/santander-back-proyecto/blob/desarrollo/src/assets/mockups/propuesta1/movil-hover.png

**Establece un tiempo limite para terminar tu feature**
> 15-08-2021 23:59 GMT

### Tareas
- [ ] Tarea 1 Crear componentes html y js
- [ ] Tarea 2 Crear invocaciones

**Solicita una mejora**
Descripción 
En caso de error, realizar ajuste según corresponda.

**Comment by 14030598** [comment]
Una pregunta, si se esta trabajando con webpack y babel??

**Comment by frasgado** [comment]
Issue concluido
