### ISSUE TITLE
Cambios en al index.html

### ISSUE THREAD

**Issue by IvanVargasJ** [14030598/santander-back-proyecto#21]
Se creara el diseño a la página basandome en los siguientes mockups.
https://github.com/14030598/santander-back-proyecto/blob/master/src/assets/mockups/propuesta1/web-inicio3.png
https://github.com/14030598/santander-back-proyecto/blob/master/src/assets/mockups/propuesta1/web-footer.png

**Establece un tiempo limite para terminar tu feature**
> 14-08-2021 23:59 GMT

### Tareas
- [x] Creación del body
- [x] Creación del footer

**Comment by 14030598** [comment]
Tomo este issue

**Comment by 14030598** [comment]
done
