### ISSUE TITLE
Video para proyecto

### ISSUE THREAD

**Issue by 14030598** [14030598/santander-back-proyecto#22]
- [ ] Duración máxima de 5 min.
- [ ] Sin errores de edición.
- [ ] Presentación de cada integrante del equipo y la explicación es clara.
- [ ] Incluye el link o código QR al repositorio y documento del proyecto.
- [ ] Exposición de los problemas a los que se enfrentaron durante el desarrollo (en caso de no haber tenido ninguno, mencionarlo).
- [ ] Incluye una descripción de los pasos que se siguieron para elaborar el proyecto.
- [ ] Muestra el resultado del proyecto tal y como se describe en las instrucciones del proyecto.

**Comment by frasgado** [comment]
Documentación y video realizado.,
Se ha capturado y enviado el formulario del proyecto 4.
