### ISSUE TITLE
Archivo webpack.config.js

### ISSUE THREAD

**Issue by 14030598** [14030598/santander-back-proyecto#6]
Esta es la primera parte de ese proyecto y consiste en dejar listo el ambiente de desarrollo:

> Configurar Webpack, Babel y Webpack Dev Server. Aunado a lo anterior; librería de estilos, sass y loaders de archivos y html

### Tareas a realizar

- [x] Configurar Webpack, Babel y Webpack Dev Server.
- [ ] Configurar loaders `html-loader`, `style-loader`, `sass-loader`, etc.

### Especificaciones
- Crear el archivo webpack.config.js

- Configurar Webpack, Babel y Webpack Dev Server.
- Se han incluido las configuraciones webpack.config.js y package.json para soporte de Webpack Server.

- Configurar los loaders necesarios para los estilos, se puede utilizar CSS o SASS.

### Información

- Issue que bloquea esté issue
#Ninguna

- Issue a desbloquear con este issue
#8

_Team 4_

**Comment by frasgado** [comment]
Se han incluido las configuraciones webpack.config.js y package.json para soporte de Webpack Server.

**Comment by 14030598** [comment]
adding loaders(sass|css|style|asset|html) en commit b722b4d3fb2af7b15abc390837c4a1c77d878f22
